### ISSUE TITLE
setting image dimensions

### ISSUE THREAD

**Issue by v0ker** [Kuari/coolCaptcha#1]
When setting the dimensions of an image to 90 * 30, the entire image is not displayed. What is the minimum aspect ratio for image to be displayed? Is it possible to scale the image proportionally?

```go
captcha: coolCaptcha.New(
	coolCaptcha.SetWidth(60),                               // set the width of the image
	coolCaptcha.SetHeight(20),                              // set the height of the image
	coolCaptcha.SetCodeType(coolCaptcha.NumericCharacters), // only number captcha
)

imageBase64Data, code, err := a.captcha.Generate()
``` 

base64image:
```
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADwAAAAUCAIAAABeYcl+AAACKklEQVR4nMSXy3LTPBSAdY7k+Hcb32qnaaftDxsY2MGWx2DJI/CEvAZLWJXS3BzbsWLn5ovEJAy0hEljxyH5RuOFRueczxpdbOZ/fE/2hwBMTsxEs3zzgjedRLNSRc2RSaQCQAJIggQIISBrVGE1LZMTKzDaA/t6pJ9PND1VtDo2JaksnTHVs6667vPAuow1K6d1X3sHSpWMT+y79sue8z9vOilT/73VFjZK51S5vXx9e/EqNM4LpIe12sK6dKS7X6/f9NxnU7V5JKXtsLHp6PHIs6++3Lwd2DdHWaNVYZ/efRA5ygPs+ZrA8qgEKajIWZHhMU1WIgAE8PdTPnSCJEDUdN4efGv371pep7GY7eGcLmm2VEEJVCLKx36bQmiRO36v5XXOve9GFBLyx8j9SwNKpKu28kMq10puDJTS5L477LpepzXsYFFsGllXGpAgip+WQAVitc0BUliRf+b3naDnDrtKuigTVV0aCKUSmUAqKJU7fESgKKyR3/Luz4L+WdBneVY1QylpAIIrUbpyrVoDpNTHoclDOxzY4cDkAYjKSR7zlDSipI1dRFmemjwweGjw0Ix8gwe0yOtYruf/uwupZEpBFQElFigKoc0SbZqcJvx0MtbjqBlHpxNecy6f5kFan/GL6M6e+wRJ1lAzRV3OMOIvuYLl2bJlaSNdqIuZOp/+N5uo6Zwc/GZiVhI4vP/i/rMdDw9ce2dgv38uh+GYd/jO/AgAAP//UxHzy8onj5EAAAAASUVORK5CYII=
```

The image is not fully displayed with the specified dimensions.

**Comment by hunter-ji** [comment]
Thanks for your feedback, this is indeed a problem. This problem will be fixed soon in the next version, and the next version will make an improvement to the security of the captcha and support dynamic effects. The next version will be available soon.

**Comment by hunter-ji** [comment]
And, your PR is very welcome!

**Comment by hunter-ji** [comment]
Sorry for waiting so long, I fixed this issue at [new version](https://github.com/Kuari/coolCaptcha/releases/tag/v1.0.1).
I have been trying to do dynamic captcha, but at present, some of the underlying schemes are not very good for concurrency support. So the new version of dynamic captcha can be used, but the performance is not good, and it takes some time to solve this problem.

**Comment by v0ker** [comment]
Thank you very much. I will try to use the new version and look forward to a better performance dynamic captcha.
